dist: trusty
sudo: false
language: perl
perl:
- "5.8"
- "5.26"
install:
- cpanm File::BaseDir
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- make -C doc/
- perl -wc elvoke
- make install PREFIX=~/.local
- cd /
- elvoke --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 elvoke | grep -A 10 -w ELVOKE

# vim:ts=2 sts=2 sw=2 et
