dist: trusty
language: perl
perl:
- "5.10"
- "5.28"
install:
- python -m pip install --user docutils
- cpanm File::BaseDir
script:
- make -C doc/
- make -C doc/ check
- perl -wc elvoke
- make install PREFIX=~/.local
- cd /
- elvoke --help
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 elvoke | grep -A 10 -w ELVOKE

# vim:ts=2 sts=2 sw=2 et
